[client]
showDeployButton = false
toolbarMode = "minimal"

[theme]
base = "light"

[toolbar]
showRerunButton = false
showClearCacheButton = false
showAboutButton = false
showReportAnIssueButton = false